# Generated by Django 3.0.4 on 2020-03-05 20:07

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200305_1630'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=400, unique=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=400, null=True, unique=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=400, null=True, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Латинские буквы и цифры, подчеркивание и дефис', max_length=150, unique=True, verbose_name='Алиас')),
            ],
            options={
                'verbose_name': 'Категория проектов',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ('ordering',),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('ordering',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент первой секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_1_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент первой секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_1_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент первой секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_1_subtitle',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Заголовок над контентом первой секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_1_subtitle_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Заголовок над контентом первой секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_1_subtitle_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Заголовок над контентом первой секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент второй секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент второй секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_1_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_1_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_2_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_2_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_3_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_image_3_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/images', verbose_name='Вторая секция: изображение 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент второй секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_subtitle',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Заголовок над контентом второй секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_subtitle_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Заголовок над контентом второй секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_2_subtitle_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Заголовок над контентом второй секции'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_title',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Заголовок блока контента'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_title_en',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Заголовок блока контента'),
        ),
        migrations.AddField(
            model_name='project',
            name='content_title_ru',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Заголовок блока контента'),
        ),
        migrations.AddField(
            model_name='project',
            name='excerpt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='excerpt_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='excerpt_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Gallery', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_bg',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_bg_color',
            field=colorfield.fields.ColorField(default='#CCCCCC', max_length=18, verbose_name='Первый экран: цвет фона'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_button_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_button_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_button_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_button_link_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_button_link_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_1_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок, колонка 1: контент'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_1_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок, колонка 1: контент'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_1_content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок, колонка 1: контент'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок, колонка 1: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_1_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок, колонка 1: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_1_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок, колонка 1: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_2_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок, колонка 2: контент'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_2_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок, колонка 2: контент'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_2_content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок, колонка 2: контент'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_2_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок, колонка 2: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_2_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок, колонка 2: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_2_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок, колонка 2: заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/list', verbose_name='Изображение в списке'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_image_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/list', verbose_name='Изображение в списке'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_image_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/list', verbose_name='Изображение в списке'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_dates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Даты проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_dates_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Даты проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_dates_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Даты проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='section_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент жирным текстом'),
        ),
        migrations.AddField(
            model_name='project',
            name='section_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент жирным текстом'),
        ),
        migrations.AddField(
            model_name='project',
            name='section_content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент жирным текстом'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_description_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_description_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)'),
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_ru', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_en', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('hero_subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_bg_color', colorfield.fields.ColorField(default='#CCCCCC', max_length=18, verbose_name='Первый экран: цвет фона')),
                ('hero_bg', models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('show_call_to_action', models.BooleanField(default=True, verbose_name='Показывать блок призыва к действию')),
                ('show_subscribe', models.BooleanField(default=True, verbose_name='Показывать блок подписки')),
                ('call_to_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CallToAction', verbose_name='Призыв к действию')),
                ('subscribe_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SubscribeBlock', verbose_name='Блок подписки')),
            ],
            options={
                'verbose_name': 'Страница проектов',
                'verbose_name_plural': 'Страница проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectSectionIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('icon', models.FileField(blank=True, max_length=255, null=True, upload_to='projects/icons', verbose_name='Иконка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_icons', to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Иконка в контенте проекта',
                'verbose_name_plural': 'Иконки в контенте проекта',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='ProjectIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=255, null=True, verbose_name='Значение')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('unit_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('unit_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Показатель проекта',
                'verbose_name_plural': 'Показатели проекта',
                'ordering': ('ordering',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.ProjectCategory', verbose_name='Категории'),
        ),
    ]
