# Generated by Django 3.0.4 on 2020-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200305_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_button_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список проектов: текст кнопки "Подробнее"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_button_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список проектов: текст кнопки "Подробнее"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_button_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список проектов: текст кнопки "Подробнее"'),
        ),
    ]
