# Generated by Django 3.0.4 on 2020-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200306_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_categories_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Категории"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_categories_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Категории"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_categories_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Категории"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_client_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Клиент"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_client_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Клиент"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_client_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Клиент"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_date_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Даты"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_date_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Даты"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='project_date_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Даты"'),
        ),
    ]
