# Generated by Django 3.0.4 on 2020-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200306_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='location_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Место проведения"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='location_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Место проведения"'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='location_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проект: текст "Место проведения"'),
        ),
    ]
