# Generated by Django 3.0.4 on 2020-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201109_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hero_button_order',
            field=models.BooleanField(default=False, verbose_name='Первый экран: кнопка открывает форму заказа'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='hero_button_order',
            field=models.BooleanField(default=False, verbose_name='Первый экран: кнопка открывает форму заказа'),
        ),
    ]
