# Generated by Django 3.0.4 on 2020-11-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calltoaction_button_order'),
        ('projects', '0007_auto_20201109_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='call_to_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.CallToAction', verbose_name='Призыв к действию'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_call_to_action',
            field=models.BooleanField(default=True, verbose_name='Показывать блок призыва к действию'),
        ),
    ]
