# Generated by Django 3.0.4 on 2020-03-05 13:30

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200305_1630'),
        ('projects', '0001_initial'),
        ('services', '0001_initial'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blog_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Блог: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Блог: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Блог: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Блог: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Блог: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Блог: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_to_action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CallToAction', verbose_name='Призыв к действию'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_bg',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_bg_color',
            field=colorfield.fields.ColorField(default='#CCCCCC', max_length=18, verbose_name='Первый экран: цвет фона'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_link_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_button_link_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_button_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_button_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_button_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_button_link_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_button_link_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 1: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 1: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 1: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_icon_1',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/icons', verbose_name='Инфоблок 1: иконка 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_icon_2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/icons', verbose_name='Инфоблок 1: иконка 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_icon_3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/icons', verbose_name='Инфоблок 1: иконка 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 1: изображение 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_image_1_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 1: изображение 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_image_1_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 1: изображение 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 1: изображение 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_image_2_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 1: изображение 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_image_2_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 1: изображение 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_1_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_button_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_button_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_button_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_button_link_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_button_link_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 2: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 2: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 2: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение под контентом'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_1_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_1_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_2_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_2_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_3_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_3_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_en',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение под контентом'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_image_ru',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 2: изображение под контентом'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_2_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 2: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_button_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_button_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_button_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_button_link_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_button_link_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 3: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 3: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфоблок 3: контент'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_icon_1',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/icons', verbose_name='Инфоблок 3: иконка 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_icon_2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/icons', verbose_name='Инфоблок 3: иконка 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_icon_3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/info/icons', verbose_name='Инфоблок 3: иконка 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 3: изображение справа'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_image_en',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 3: изображение справа'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_image_ru',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home/info/images', verbose_name='Инфоблок 3: изображение справа'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_3_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 3: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/services/icons', verbose_name='Услуги: иконка'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Услуги: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Услуги: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Услуги: над заголовком'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Услуги: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Услуги: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Услуги: заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_blog',
            field=models.BooleanField(default=True, verbose_name='Показывать блок блога'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_brands',
            field=models.BooleanField(default=True, verbose_name='Показывать блок брендов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_call_to_action',
            field=models.BooleanField(default=True, verbose_name='Показывать блок призыва к действию'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_info_1',
            field=models.BooleanField(default=True, verbose_name='Показывать инфоблок 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_info_2',
            field=models.BooleanField(default=True, verbose_name='Показывать инфоблок 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_info_3',
            field=models.BooleanField(default=True, verbose_name='Показывать инфоблок 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_projects',
            field=models.BooleanField(default=True, verbose_name='Показывать блок анонсов проектов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_services',
            field=models.BooleanField(default=True, verbose_name='Показывать блок анонсов услуг'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_subscribe',
            field=models.BooleanField(default=True, verbose_name='Показывать блок подписки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SubscribeBlock', verbose_name='Блок подписки'),
        ),
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('image', models.FileField(max_length=255, upload_to='home/services/images', verbose_name='Изображение')),
                ('image_ru', models.FileField(max_length=255, null=True, upload_to='home/services/images', verbose_name='Изображение')),
                ('image_en', models.FileField(max_length=255, null=True, upload_to='home/services/images', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('content_ru', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('content_en', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homepage.HomePage', verbose_name='Страница')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга на главной',
                'verbose_name_plural': 'Услуги на главной',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(max_length=255, upload_to='home/projects', verbose_name='Изображение')),
                ('image_ru', models.ImageField(max_length=255, null=True, upload_to='home/projects', verbose_name='Изображение')),
                ('image_en', models.ImageField(max_length=255, null=True, upload_to='home/projects', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('categories', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категории')),
                ('categories_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категории')),
                ('categories_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категории')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='homepage.HomePage', verbose_name='Страница')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Проект на главной',
                'verbose_name_plural': 'Проекты на главной',
                'ordering': ('ordering',),
            },
        ),
    ]
