# Generated by Django 3.0.4 on 2020-03-05 16:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200305_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blog_subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Блог: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blog_subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Блог: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blog_subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Блог: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_1_subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 1: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_1_subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 1: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_1_subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 1: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_2_subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 2: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_2_subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 2: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_2_subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 2: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_3_subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 3: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_3_subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 3: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_3_subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Инфоблок 3: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Услуги: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Услуги: над заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_subtitle_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1024, null=True, verbose_name='Услуги: над заголовком'),
        ),
    ]
