# Generated by Django 3.0.4 on 2020-03-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200305_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebrand',
            options={'ordering': ('ordering',), 'verbose_name': 'Бренд на главной', 'verbose_name_plural': 'Бренды на главной'},
        ),
    ]
