# Generated by Django 3.0.4 on 2020-03-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200306_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='info_1_title',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_1_title_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='info_1_title_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Инфоблок 1: заголовок'),
        ),
    ]
