# Generated by Django 3.0.4 on 2020-03-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200306_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproject',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='categories_en',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='categories_ru',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='title',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='title_ru',
        ),
    ]
