# Generated by Django 3.0.4 on 2020-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20200306_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_button_order',
            field=models.BooleanField(default=False, verbose_name='Первый экран: кнопка открывает форму заказа'),
        ),
    ]
