# Generated by Django 3.0.4 on 2022-02-22 19:37

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20220203_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_bg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_bg_color',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_bg_mobile',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_bg_opacity',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_caption',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_caption_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_caption_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_content_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_content_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_link_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_link_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_order',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_script',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_script_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_script_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_ru',
        ),
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('hero_subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_order', models.BooleanField(default=False, verbose_name='Первый экран: кнопка открывает форму заказа')),
                ('hero_button_content', models.TextField(blank=True, null=True, verbose_name='Первый экран: HTML-контент кнопки')),
                ('hero_button_content_ru', models.TextField(blank=True, null=True, verbose_name='Первый экран: HTML-контент кнопки')),
                ('hero_button_content_en', models.TextField(blank=True, null=True, verbose_name='Первый экран: HTML-контент кнопки')),
                ('hero_button_script', models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт для кнопки')),
                ('hero_button_script_ru', models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт для кнопки')),
                ('hero_button_script_en', models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт для кнопки')),
                ('hero_bg_color', colorfield.fields.ColorField(default='#CCCCCC', max_length=18, verbose_name='Первый экран: цвет фона')),
                ('hero_bg', models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона')),
                ('hero_bg_mobile', models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона (мобильные)')),
                ('hero_bg_opacity', models.FloatField(default=0.1, help_text='больше - светлее', verbose_name='Первый экран: прозрачность фонового изображения')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='homepage.HomePage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды первого экрана',
                'ordering': ('ordering',),
            },
        ),
    ]
