# Generated by Django 3.0.4 on 2020-03-05 17:22

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200305_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_ru', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_en', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('hero_subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_bg_color', colorfield.fields.ColorField(default='#CCCCCC', max_length=18, verbose_name='Первый экран: цвет фона')),
                ('hero_bg', models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона')),
                ('show_map', models.BooleanField(default=True, verbose_name='Показывать карту')),
                ('map_latitude', models.FloatField(blank=True, null=True, verbose_name='Карта: широта')),
                ('map_longitude', models.FloatField(blank=True, null=True, verbose_name='Карта: долгота')),
                ('map_altitude', models.PositiveSmallIntegerField(default=15, verbose_name='Карта: альтитуда карты')),
                ('show_form', models.BooleanField(default=True, verbose_name='Показывать форму')),
                ('form_icon', models.FileField(blank=True, max_length=255, null=True, upload_to='contacts/icons', verbose_name='Форма: иконка')),
                ('form_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ')),
                ('form_subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ')),
                ('form_subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ')),
                ('form_title', models.TextField(blank=True, max_length=255, null=True, verbose_name='Форма: заголовок')),
                ('form_title_ru', models.TextField(blank=True, max_length=255, null=True, verbose_name='Форма: заголовок')),
                ('form_title_en', models.TextField(blank=True, max_length=255, null=True, verbose_name='Форма: заголовок')),
                ('form_name_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля имени')),
                ('form_name_label_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля имени')),
                ('form_name_label_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля имени')),
                ('form_email_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля email')),
                ('form_email_label_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля email')),
                ('form_email_label_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля email')),
                ('form_phone_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля телефона')),
                ('form_phone_label_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля телефона')),
                ('form_phone_label_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля телефона')),
                ('form_message_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля сообщения')),
                ('form_message_label_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля сообщения')),
                ('form_message_label_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: ярлык поля сообщения')),
                ('form_button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: текст кнопки')),
                ('form_button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: текст кнопки')),
                ('form_button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма: текст кнопки')),
                ('show_subscribe', models.BooleanField(default=True, verbose_name='Показывать блок подписки')),
                ('subscribe_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SubscribeBlock', verbose_name='Блок подписки')),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': 'Страница контактов',
            },
        ),
        migrations.CreateModel(
            name='ContactBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('icon', models.FileField(blank=True, max_length=255, null=True, upload_to='contacts/icons', verbose_name='Иконка')),
                ('line_1', models.TextField(blank=True, null=True, verbose_name='Строка 1')),
                ('line_2', models.TextField(blank=True, null=True, verbose_name='Строка 2')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_blocks', to='contacts.ContactsPage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок контактов',
                'verbose_name_plural': 'Блоки контактов',
                'ordering': ('ordering',),
            },
        ),
    ]
