# Generated by Django 3.0.4 on 2020-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201109_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='hero_button_order',
            field=models.BooleanField(default=False, verbose_name='Первый экран: кнопка открывает форму заказа'),
        ),
    ]
