# Generated by Django 3.0.4 on 2020-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200305_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='service_button_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список услуг: текст кнопки "Подробнее"'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_button_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список услуг: текст кнопки "Подробнее"'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='service_button_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Список услуг: текст кнопки "Подробнее"'),
        ),
    ]
