# Generated by Django 3.0.4 on 2020-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200306_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Об услуге: заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Об услуге: заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='about_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Об услуге: заголовок'),
        ),
    ]
