# Generated by Django 3.0.4 on 2022-02-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20201111_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_bg_mobile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона (мобильные)'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_bg_opacity',
            field=models.FloatField(default=0.1, help_text='больше - светлее', verbose_name='Первый экран: прозрачность фонового изображения'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_button_script',
            field=models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт кнопки'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_button_script_en',
            field=models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт кнопки'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_button_script_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт кнопки'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_bg_mobile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона (мобильные)'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_bg_opacity',
            field=models.FloatField(default=0.1, help_text='больше - светлее', verbose_name='Первый экран: прозрачность фонового изображения'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_button_script',
            field=models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт кнопки'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_button_script_en',
            field=models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт кнопки'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_button_script_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Первый экран: скрипт кнопки'),
        ),
    ]
