# Generated by Django 3.0.4 on 2020-03-05 13:30

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_ru', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_en', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('hero_subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_bg_color', colorfield.fields.ColorField(default='#CCCCCC', max_length=18, verbose_name='Первый экран: цвет фона')),
                ('hero_bg', models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона')),
            ],
            options={
                'verbose_name': 'Страница о компании',
                'verbose_name_plural': 'Страница о компании',
            },
        ),
    ]
