# Generated by Django 3.0.4 on 2020-11-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200305_1630'),
        ('about', '0003_auto_20200305_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='show_subscribe',
            field=models.BooleanField(default=True, verbose_name='Показывать блок подписки'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subscribe_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SubscribeBlock', verbose_name='Блок подписки'),
        ),
    ]
