# Generated by Django 3.0.4 on 2020-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('logo', models.FileField(max_length=255, upload_to='home/brands', verbose_name='Логотип')),
                ('logo_ru', models.FileField(max_length=255, null=True, upload_to='home/brands', verbose_name='Логотип')),
                ('logo_en', models.FileField(max_length=255, null=True, upload_to='home/brands', verbose_name='Логотип')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сссылка')),
                ('link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сссылка')),
                ('link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сссылка')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('ordering',),
            },
        ),
    ]
