# Generated by Django 3.0.4 on 2020-03-04 17:06

from django.db import migrations, models
import django.db.models.deletion
import snippets.admin.admin
import vars.service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('key', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Ключ')),
                ('verbose_title', models.CharField(max_length=250, verbose_name='Что означает')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('value_ru', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('value_en', models.TextField(blank=True, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные шаблонов',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('work_title', models.CharField(db_index=True, max_length=255, verbose_name='Рабочий заголовок')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Латинские буквы и цифры, подчеркивание и дефис', unique=True, verbose_name='Алиас')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ('ordering',),
            },
            bases=(snippets.admin.admin.SuperUserDeletableAdminMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins', models.TextField(default=vars.service.get_default_admins, help_text='через запятую, без пробелов', verbose_name='Администраторы сайта')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('phone_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('phone_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон 2')),
                ('phone_2_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон 2')),
                ('phone_2_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон 2')),
                ('phone_2_hint', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон 2: подпись')),
                ('phone_2_hint_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон 2: подпись')),
                ('phone_2_hint_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон 2: подпись')),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Публичный email')),
                ('public_email_ru', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Публичный email')),
                ('public_email_en', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Публичный email')),
                ('copyrights', models.TextField(blank=True, null=True, verbose_name='Копирайт')),
                ('copyrights_ru', models.TextField(blank=True, null=True, verbose_name='Копирайт')),
                ('copyrights_en', models.TextField(blank=True, null=True, verbose_name='Копирайт')),
                ('subscribe_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока подписки')),
                ('subscribe_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока подписки')),
                ('subscribe_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока подписки')),
                ('agree_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст соглашения о конфиденциальности под формой')),
                ('agree_text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст соглашения о конфиденциальности под формой')),
                ('agree_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст соглашения о конфиденциальности под формой')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('url_ru', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
                ('url_en', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS-класс для ссылки (а):')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vars.Menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ('ordering',),
            },
            bases=(snippets.admin.admin.SuperUserDeletableAdminMixin, models.Model),
        ),
    ]
