# Generated by Django 3.0.4 on 2020-03-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0003_auto_20200306_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_contacts_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подвал: заголовок колонки контактов'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_contacts_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подвал: заголовок колонки контактов'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_contacts_title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подвал: заголовок колонки контактов'),
        ),
    ]
