# Generated by Django 3.0.4 on 2020-03-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0004_auto_20200306_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='phone_2_hint',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='phone_2_hint_en',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='phone_2_hint_ru',
        ),
    ]
