# Generated by Django 3.0.4 on 2020-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0005_auto_20200306_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_button_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: текст кнопки'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_button_caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: текст кнопки'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_button_caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: текст кнопки'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_email_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля email'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_email_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля email'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_email_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля email'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_icon',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='contacts/icons', verbose_name='Форма заказа: иконка'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_message_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля сообщения'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_message_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля сообщения'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_message_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля сообщения'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_name_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля имени'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_name_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля имени'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_name_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля имени'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_phone_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля телефона'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_phone_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля телефона'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_phone_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля телефона'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: подзаголовок'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: подзаголовок'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: подзаголовок'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_title',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_title_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_title_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: заголовок'),
        ),
    ]
