# Generated by Django 3.0.4 on 2022-02-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0007_orderrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_role_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля роли'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_role_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля роли'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='order_form_role_label_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма заказа: ярлык поля роли'),
        ),
    ]
