# Generated by Django 3.0.4 on 2020-03-04 17:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(db_index=True, help_text='Для идентификации в административной части сайта', max_length=255, verbose_name='Рабочее название')),
                ('title_ru', models.CharField(db_index=True, help_text='Для идентификации в административной части сайта', max_length=255, null=True, verbose_name='Рабочее название')),
                ('title_en', models.CharField(db_index=True, help_text='Для идентификации в административной части сайта', max_length=255, null=True, verbose_name='Рабочее название')),
                ('publish_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Можно задать на будущее', verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galleries/images', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Галерея фотографий',
                'verbose_name_plural': 'Галереи фотографий',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(upload_to='galleries/photos/%Y/%m/%d', verbose_name='Фотография')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Текст вместо фото (alt)')),
                ('alt_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст вместо фото (alt)')),
                ('alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст вместо фото (alt)')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание фото')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание фото')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание фото')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.Gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Фотография галереи',
                'verbose_name_plural': 'Фотографии галереи',
            },
        ),
    ]
