# Generated by Django 3.0.4 on 2020-11-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200305_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='button_order',
            field=models.BooleanField(default=False, verbose_name='Кнопка открывает форму заказа'),
        ),
    ]
