# Generated by Django 3.0.4 on 2020-03-05 20:32

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200305_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_ru', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_en', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('hero_subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_bg_color', colorfield.fields.ColorField(default='#CCCCCC', max_length=18, verbose_name='Первый экран: цвет фона')),
                ('hero_bg', models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона')),
                ('publish_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Можно задать на будущее', verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='articles/%Y/%m/', verbose_name='Изображение')),
                ('list_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='articles/list/%Y/%m/', verbose_name='Изображение для анонса')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt изображения')),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt изображения')),
                ('image_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt изображения')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Латинские буквы и цифры, подчеркивание и дефис', max_length=150, unique=True, verbose_name='Алиас')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('ordering', '-publish_date'),
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='META заголовок (title)')),
                ('seo_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_ru', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('seo_description_en', models.TextField(blank=True, max_length=1024, null=True, verbose_name='META описание (description)')),
                ('hero_subtitle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_subtitle_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Первый экран: Над заголовком')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: заголовок')),
                ('hero_button_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: текст кнопки')),
                ('hero_button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_button_link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый экран: ссылка кнопки')),
                ('hero_bg_color', colorfield.fields.ColorField(default='#CCCCCC', max_length=18, verbose_name='Первый экран: цвет фона')),
                ('hero_bg', models.FileField(blank=True, max_length=255, null=True, upload_to='home/bg', verbose_name='Первый экран: изображение фона')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('show_subscribe', models.BooleanField(default=True, verbose_name='Показывать блок подписки')),
                ('subscribe_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SubscribeBlock', verbose_name='Блок подписки')),
            ],
            options={
                'verbose_name': 'Страница блога',
                'verbose_name_plural': 'Страница блога',
            },
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок секции')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('has_bg', models.BooleanField(default=False, verbose_name='С фоном')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.Article', verbose_name='Статья')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Gallery', verbose_name='Галерея фотографий')),
            ],
            options={
                'verbose_name': 'Секция статьи',
                'verbose_name_plural': 'Секции статьи',
                'ordering': ('ordering',),
            },
        ),
    ]
