# Generated by Django 3.0.4 on 2020-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_on_home',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной странице'),
        ),
    ]
