# Generated by Django 3.0.4 on 2020-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hero_button_order',
            field=models.BooleanField(default=False, verbose_name='Первый экран: кнопка открывает форму заказа'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='hero_button_order',
            field=models.BooleanField(default=False, verbose_name='Первый экран: кнопка открывает форму заказа'),
        ),
    ]
