# Generated by Django 3.0.4 on 2022-02-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0007_orderrole'),
        ('forms', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vars.OrderRole', verbose_name='Роль'),
        ),
    ]
